import fs from 'fs';
import path from 'path';
import type { Metadata } from 'next';
import DirectoryFilter, { SpeciesData, CategoryData } from './DirectoryFilter';

export const dynamic = 'force-static';

export const metadata: Metadata = {
    title: "The Complete Pet Symptom & Health Database | CheckPet",
    description: "Search our comprehensive directory of pet symptoms, breed-specific traits, and behavioral conditions to find immediate, actionable answers for your dog or cat."
};

const CATEGORY_ORDER = [
    "Injuries & Trauma",
    "Dietary & Toxins",
    "Symptoms & Illness",
    "Dermatology & Skin",
    "Behavioral & Training",
    "Breeds & Genetics",
    "Other"
];

async function getDirectoryData(): Promise<SpeciesData[]> {
    const symptomsDir = path.join(process.cwd(), 'src/data/pages');
    const filenames = fs.readdirSync(symptomsDir);

    // Load directory map generated by AI script
    let directoryMap: Record<string, string> = {};
    const mapPath = path.join(process.cwd(), 'src/data/directory-map.json');
    if (fs.existsSync(mapPath)) {
        directoryMap = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
    }

    const speciesGrouped: Record<'Dogs' | 'Cats', Record<string, { slug: string, name: string }[]>> = {
        Dogs: {},
        Cats: {}
    };

    filenames.forEach((filename) => {
        if (!filename.endsWith('.json')) return;

        const slug = filename.replace('.json', '');
        const parts = slug.split('-');

        let species: 'Dogs' | 'Cats' | null = null;
        if (parts[0] === 'dog') species = 'Dogs';
        else if (parts[0] === 'cat') species = 'Cats';

        if (!species) return;

        const symptomName = parts.slice(1).join(' ');
        const displayName = symptomName.charAt(0).toUpperCase() + symptomName.slice(1);

        let categoryName = directoryMap[slug] || 'Other';
        // Validate category
        if (!CATEGORY_ORDER.includes(categoryName)) {
            categoryName = 'Other';
        }

        if (!speciesGrouped[species][categoryName]) {
            speciesGrouped[species][categoryName] = [];
        }

        speciesGrouped[species][categoryName].push({
            slug,
            name: displayName
        });
    });

    const result: SpeciesData[] = [];

    for (const species of ['Dogs', 'Cats'] as const) {
        const categories: CategoryData[] = [];
        for (const catName of CATEGORY_ORDER) {
            if (speciesGrouped[species][catName] && speciesGrouped[species][catName].length > 0) {
                // sort items internally
                categories.push({
                    name: catName,
                    items: speciesGrouped[species][catName].sort((a, b) => a.name.localeCompare(b.name))
                });
            }
        }
        result.push({
            name: species,
            categories
        });
    }

    return result;
}

export default async function DirectoryPage() {
    const data = await getDirectoryData();

    // Generate JSON-LD schema based on the data
    const jsonLd = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": "Pet Health Directory",
        "description": "Comprehensive directory of pet symptoms, conditions, and health topics.",
        "url": "https://checkpet.vet/check",
        "about": data.map((species) => ({
            "@type": "ItemList",
            "name": `${species.name} Health Topics`,
            "itemListElement": species.categories.map((cat, idx) => ({
                "@type": "ListItem",
                "position": idx + 1,
                "name": cat.name,
                "url": `https://checkpet.vet/check#${cat.name.replace(/\s+/g, '-').toLowerCase()}`,
                "numberOfItems": cat.items.length
            }))
        }))
    };

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />
            <DirectoryFilter data={data} />
        </>
    );
}
