export const DOG_BREEDS = [
    "Mixed Breed",
    "Labrador Retriever",
    "French Bulldog",
    "German Shepherd",
    "Golden Retriever",
    "Bulldog",
    "Poodle",
    "Beagle",
    "Rottweiler",
    "Dachshund",
    "German Shorthaired Pointer",
    "Pembroke Welsh Corgi",
    "Australian Shepherd",
    "Yorkshire Terrier",
    "Cavalier King Charles Spaniel",
    "Doberman Pinscher",
    "Boxer",
    "Miniature Schnauzer",
    "Cane Corso",
    "Great Dane",
    "Shih Tzu",
    "Siberian Husky",
    "Bernese Mountain Dog",
    "Pomeranian",
    "Boston Terrier",
    "Havanese",
    "English Springer Spaniel",
    "Shetland Sheepdog",
    "Brittany",
    "Cocker Spaniel",
    "Border Collie",
    "Miniature American Shepherd",
    "Belgian Malinois",
    "Vizsla",
    "Chihuahua",
    "Pug",
    "Basset Hound",
    "Mastiff",
    "Maltese",
    "Collie",
    "English Cocker Spaniel",
    "Rhodesian Ridgeback",
    "Newfoundland",
    "Shiba Inu",
    "Weimaraner",
    "West Highland White Terrier",
    "Bichon Frise",
    "Bloodhound",
    "Other"
];

export const CAT_BREEDS = [
    "Mixed Breed (Domestic Short Hair)",
    "Mixed Breed (Domestic Long Hair)",
    "Ragdoll",
    "Maine Coon",
    "Devon Rex",
    "Exotic Shorthair",
    "Persian",
    "British Shorthair",
    "Abyssinian",
    "Scottish Fold",
    "Sphynx",
    "Siamese",
    "Cornish Rex",
    "Norwegian Forest Cat",
    "American Shorthair",
    "Bengal",
    "Russian Blue",
    "Siberian",
    "Burmese",
    "Birman",
    "Tonkinese",
    "Oriental Shorthair",
    "Selkirk Rex",
    "Ragamuffin",
    "American Wirehair",
    "Chartreux",
    "Bombay",
    "Himalayan",
    "Manx",
    "Somali",
    "Turkish Angora",
    "Other"
];
