-- Enable pg_cron for scheduling SMS checks
create extension if not exists "pg_cron" with schema "extensions";

-- Enable pg_net for making HTTP requests from Cron
create extension if not exists "pg_net" with schema "extensions";

-- Create the triage_cases table
create table "public"."triage_cases" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone default now(),
    "symptoms" text,
    "ai_analysis" jsonb,
    "urgency_level" text,
    "client_phone_number" text,
    "monitor_opt_in" boolean default false,
    "follow_up_time" timestamp with time zone,
    "follow_up_sent" boolean default false,
    "outcome_status" text,
    "monitoring_history" jsonb default '[]'::jsonb,
    constraint "triage_cases_pkey" primary key ("id")
);

-- Enable Row Level Security
alter table "public"."triage_cases" enable row level security;

-- Policy: Allow anonymous users to INSERT new cases (generated by AI)
create policy "Enable insert for anon users"
on "public"."triage_cases"
as permissive
for insert
to anon
with check (true);

-- Policy: Allow anonymous users to UPDATE their own case (e.g. adding phone number)
-- Note: In a real app, we might check a session token, but for this anonymous MVP, 
-- we rely on the specific case_id being known by the client.
create policy "Enable update for anon users via ID"
on "public"."triage_cases"
as permissive
for update
to anon
using (true)
with check (true);

-- Policy: Allow anon to SELECT (needed for reading back if necessary)
create policy "Enable select for anon users"
on "public"."triage_cases"
as permissive
for select
to anon
using (true);

-- Schedule the Cron Job to run every 10 minutes
-- It calls the 'send-scheduled-sms' Edge Function
-- REPLACE 'PROJECT_REF' and 'SERVICE_KEY' with actual values in production, 
-- but for local dev / Supabase managed, we often use internal networking or specific setup.
-- For this migration, we will assume standard invocation.

select cron.schedule(
    'process-monitoring-queue',
    '*/10 * * * *',
    $$
    select net.http_post(
        url:='https://project_ref.supabase.co/functions/v1/send-scheduled-sms',
        headers:='{"Content-Type": "application/json", "Authorization": "Bearer service_role_key"}'
    ) as request_id;
    $$
);
